import yaml

def read_config(file_path):
    with open(file_path, 'r') as f:
        cfg = yaml.load(f, Loader=yaml.FullLoader)

    global POPULATION_SIZE
    global INITIALIZATION_DUPLICATION
    global TOURNAMENT_SIZE
    global TOURNAMENT_WITH_REPLACEMENT
    global CROSSOVER_RATE
    global MUTATION_RATE
    global MUTATION_ADD_RATE
    global MUTATION_DEL_RATE
    global CROSSOVER_THRESHOLD
    global START_REGULATORY_SIZE
    global MIN_SPECIES_SIZE
    global START_SPECIES_THRESHOLD
    global SPECIES_THRESHOLD_UPDATE
    global MIN_SPECIES_THRESHOLD
    global MAX_SPECIES_THRESHOLD
    global ID_COEF
    global ENH_COEF
    global INH_COEF
    global MAX_SELECTION_TRIES
    global BETA_MIN
    global BETA_MAX
    global DELTA_MIN
    global DELTA_MAX
    
    POPULATION_SIZE = cfg['POPULATION_SIZE']
    INITIALIZATION_DUPLICATION = cfg['INITIALIZATION_DUPLICATION']
    TOURNAMENT_SIZE =  cfg['TOURNAMENT_SIZE']
    TOURNAMENT_WITH_REPLACEMENT = cfg['TOURNAMENT_WITH_REPLACEMENT']
    CROSSOVER_RATE = cfg['CROSSOVER_RATE']
    MUTATION_RATE = cfg['MUTATION_RATE']
    MUTATION_ADD_RATE = cfg['MUTATION_ADD_RATE']
    MUTATION_DEL_RATE = cfg['MUTATION_DEL_RATE']
    CROSSOVER_THRESHOLD = cfg['CROSSOVER_THRESHOLD']
    START_REGULATORY_SIZE = cfg['START_REGULATORY_SIZE']
    MIN_SPECIES_SIZE = cfg['MIN_SPECIES_SIZE']
    START_SPECIES_THRESHOLD = cfg['START_SPECIES_THRESHOLD']
    SPECIES_THRESHOLD_UPDATE = cfg['SPECIES_THRESHOLD_UPDATE']
    MIN_SPECIES_THRESHOLD = cfg['MIN_SPECIES_THRESHOLD']
    MAX_SPECIES_THRESHOLD = cfg['MAX_SPECIES_THRESHOLD']
    ID_COEF = cfg['ID_COEF']
    ENH_COEF = cfg['ENH_COEF']
    INH_COEF = cfg['INH_COEF']
    MAX_SELECTION_TRIES = cfg['MAX_SELECTION_TRIES']
    BETA_MIN = cfg['BETA_MIN']
    BETA_MAX = cfg['BETA_MAX']
    DELTA_MIN = cfg['DELTA_MIN']
    DELTA_MAX = cfg['DELTA_MAX']

    return cfg


POPULATION_SIZE = 500
INITIALIZATION_DUPLICATION = 10
TOURNAMENT_SIZE = 3
TOURNAMENT_WITH_REPLACEMENT = True
CROSSOVER_RATE = 0.25
MUTATION_RATE = 0.75
MUTATION_ADD_RATE = 0.5
MUTATION_DEL_RATE = 0.25
CROSSOVER_THRESHOLD = 0.15
START_REGULATORY_SIZE = 1
MIN_SPECIES_SIZE = 5
START_SPECIES_THRESHOLD = 0.15
SPECIES_THRESHOLD_UPDATE = 0.01
MIN_SPECIES_THRESHOLD = 0.03
MAX_SPECIES_THRESHOLD = 0.5
ID_COEF = 0.75
ENH_COEF = 0.125
INH_COEF = 0.125
MAX_SELECTION_TRIES = 10
BETA_MIN = 0.05
BETA_MAX = 2.0
DELTA_MIN = 0.05
DELTA_MAX = 2.0